# Generated by Django 3.1.2 on 2020-10-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.CharField(help_text='X', max_length=100)),
                ('Y', models.CharField(help_text='Y', max_length=100)),
            ],
        ),
    ]
