# Generated by Django 3.1.2 on 2020-10-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.CharField(help_text='X', max_length=100)),
                ('Y', models.CharField(help_text='Y', max_length=100)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=29)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift', max_length=20)),
                ('Date', models.CharField(blank=True, help_text='Date', max_length=100, null=True)),
                ('Age', models.CharField(blank=True, choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult'), (None, '')], default='Juvenile', help_text='Age', max_length=20)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray'), (None, '')], help_text='Primary Fur Color', max_length=15)),
                ('Location', models.CharField(blank=True, choices=[('Above_Ground', 'Above_Ground'), ('Ground_Plane', 'Ground_Plane'), (None, '')], help_text='Location', max_length=100)),
                ('Specific_Location', models.CharField(blank=True, help_text='Specific Location', max_length=150)),
                ('Running', models.BooleanField(default=False, help_text='Whether or not squirrel is running')),
                ('Chasing', models.BooleanField(default=False, help_text='Whether or not squirrel is chasing')),
                ('Climbing', models.BooleanField(default=False, help_text='Whether or not squirrel is climbing')),
                ('Eating', models.BooleanField(default=False, help_text='Whether or not squirrel is eating')),
                ('Foraging', models.BooleanField(default=False, help_text='Whether or not squirrel is foraging')),
                ('Other_Activities', models.CharField(blank=True, help_text='Other Activities', max_length=150, null=True)),
                ('Kuks', models.BooleanField(default=False, help_text='Whether or not squirrel is kuks')),
                ('Quaas', models.BooleanField(default=False, help_text='Whether or not squirrel is quaas')),
                ('Moans', models.BooleanField(default=False, help_text='Whether or not squirrel is moans')),
                ('Tail_flags', models.BooleanField(default=False, help_text='Whether or not squirrel is tail flags')),
                ('Tail_twitches', models.BooleanField(default=False, help_text='Whether or not squirrel is tail twitches')),
                ('Approaches', models.BooleanField(default=False, help_text='Whether or not squirrel is approaches')),
                ('Indifferent', models.BooleanField(default=False, help_text='Whether or not squirrel is indiferent')),
                ('Runs_from', models.BooleanField(default=False, help_text='Whether or not squirrel is runs from')),
            ],
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
