# Generated by Django 3.1.2 on 2020-10-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.CharField(help_text='X', max_length=100)),
                ('Y', models.CharField(help_text='Y', max_length=100)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=100)),
                ('Hectare', models.CharField(help_text='Hectare', max_length=100)),
                ('Shift', models.CharField(help_text='Shift', max_length=100)),
                ('Date', models.CharField(help_text='Date', max_length=100)),
                ('Hectare_Squirrel_Number', models.CharField(help_text='Hectare Squirrel Number', max_length=100)),
                ('Age', models.CharField(blank=True, help_text='Age', max_length=100)),
                ('Primary_Fur_Color', models.CharField(blank=True, help_text='Primary Fur Color', max_length=100)),
                ('Highlight_Fur_Color', models.CharField(blank=True, help_text='Highlight Fur Color', max_length=100)),
                ('Combination_of_Primary_and_Highlight_Color', models.CharField(help_text='Combination of Primary and Highlight Color', max_length=100)),
                ('Color_notes', models.CharField(blank=True, help_text='Color notes', max_length=100)),
                ('Location', models.CharField(blank=True, help_text='Location', max_length=100)),
                ('Above_Ground_Sighter_Measurement', models.CharField(blank=True, help_text='Above Ground Sighter Measurement', max_length=100)),
                ('Specific_Location', models.CharField(blank=True, help_text='Specific Location', max_length=100)),
                ('Running', models.BooleanField(help_text='Whether or not squirrel is running')),
                ('Chasing', models.BooleanField(help_text='Whether or not squirrel is chasing')),
                ('Climbing', models.BooleanField(help_text='Whether or not squirrel is climbing')),
                ('Eating', models.BooleanField(help_text='Whether or not squirrel is eating')),
                ('Foraging', models.BooleanField(help_text='Whether or not squirrel is foraging')),
                ('Other_Activities', models.CharField(blank=True, help_text='Other Activities', max_length=100)),
                ('Kuks', models.BooleanField(help_text='Whether or not squirrel is kuks')),
                ('Quaas', models.BooleanField(help_text='Whether or not squirrel is quaas')),
                ('Moans', models.BooleanField(help_text='Whether or not squirrel is moans')),
                ('Tail_flags', models.BooleanField(help_text='Whether or not squirrel is tail flags')),
                ('Tail_twitches', models.BooleanField(help_text='Whether or not squirrel is tail twitches')),
                ('Approaches', models.BooleanField(help_text='Whether or not squirrel is approaches')),
                ('Indifferent', models.BooleanField(help_text='Whether or not squirrel is indiferent')),
                ('Runs_from', models.BooleanField(help_text='Whether or not squirrel is runs from')),
                ('Other_interactions', models.CharField(blank=True, help_text='Other interactions', max_length=100)),
                ('Lat_Long', models.CharField(help_text='Lat/Long', max_length=100)),
            ],
        ),
    ]
