# Generated by Django 3.1.2 on 2020-10-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='Above_Ground_Sighter_Measurement',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Color_notes',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Combination_of_Primary_and_Highlight_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Hectare',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Hectare_Squirrel_Number',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Highlight_Fur_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Lat_Long',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Other_interactions',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult'), (None, '')], default='Juvenile', help_text='Age', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is approaches'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is chasing'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is climbing'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.CharField(blank=True, help_text='Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is eating'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is foraging'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is indiferent'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is kuks'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, choices=[('Above_Ground', 'Above_Ground'), ('Ground_Plane', 'Ground_Plane'), (None, '')], help_text='Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is moans'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Other_Activities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray'), (None, '')], help_text='Primary Fur Color', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is quaas'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is running'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_from',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is runs from'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Specific_Location',
            field=models.CharField(blank=True, help_text='Specific Location', max_length=150),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is tail flags'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is tail twitches'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=29),
        ),
    ]
