# Generated by Django 3.1.2 on 2020-10-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20201021_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='X',
            field=models.DecimalField(decimal_places=15, help_text='X', max_digits=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Y',
            field=models.DecimalField(decimal_places=15, help_text='Y', max_digits=100),
        ),
    ]
