# Generated by Django 3.1.2 on 2020-10-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.CharField(help_text='Whether or not squirrel is approaches', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.CharField(help_text='Whether or not squirrel is chasing', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.CharField(help_text='Whether or not squirrel is climbing', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.CharField(help_text='Whether or not squirrel is eating', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.CharField(help_text='Whether or not squirrel is foraging', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.CharField(help_text='Whether or not squirrel is indiferent', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.CharField(help_text='Whether or not squirrel is kuks', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.CharField(help_text='Whether or not squirrel is moans', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.CharField(help_text='Whether or not squirrel is quaas', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.CharField(help_text='Whether or not squirrel is running', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_from',
            field=models.CharField(help_text='Whether or not squirrel is runs from', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.CharField(help_text='Whether or not squirrel is tail flags', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.CharField(help_text='Whether or not squirrel is tail twitches', max_length=100),
        ),
    ]
