# Generated by Django 3.1.2 on 2020-10-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20201017_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult'), ('Other', 'Other')], default='Juvenile', help_text='Age', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is approaches'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is chasing'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is climbing'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(help_text='Date', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is eating'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is foraging'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is indiferent'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is kuks'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, choices=[('Above_Ground', 'Above_Ground'), ('Ground_Plane', 'Ground_Plane'), ('Other', 'Other')], default='Other', help_text='Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is moans'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray'), ('Other', 'Other')], default='Other', help_text='Primary Fur Color', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is quaas'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is running'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_from',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is runs from'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is tail flags'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel is tail twitches'),
        ),
    ]
