# Generated by Django 3.1.2 on 2020-10-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0003_auto_20201018_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='Above_Ground_Sighter_Measurement',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Color_notes',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Combination_of_Primary_and_Highlight_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Hectare',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Hectare_Squirrel_Number',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Highlight_Fur_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Lat_Long',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Other_interactions',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.CharField(help_text='Date', max_length=100),
        ),
    ]
