# Generated by Django 3.1.2 on 2020-10-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20201018_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray'), ('Other', 'Other')], default='Other', help_text='Primary Fur Color', max_length=15),
        ),
    ]
