# Generated by Django 3.1.2 on 2020-10-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0006_auto_20201019_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=29),
        ),
    ]
